<?php

namespace AppBundle\Repository;

/**
 * TodoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TodoRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByUserId($userid)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT t FROM AppBundle:Todo t WHERE t.user_id = :userid ORDER BY t.id ASC'
            )->setParameter('userid', $userid)
            ->getResult();
    }
}
