<?php

namespace AppBundle\Repository;

/**
 * TrashRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrashRepository extends \Doctrine\ORM\EntityRepository
{
}
